#!/bin/bash

echo "================================"
echo "Battle of Sea - Full Run Setup"
echo "================================"
echo ""
echo "Откройте 3 терминала и запустите в каждом:"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Terminal 1 - СЕРВЕР:"
echo "═══════════════════════════════════════════════════════════════"
echo "cd /Users/masha/battle_of_sea/battle_of_sea"
echo "dotnet run --project battle_of_sea/battle_of_sea.csproj"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Terminal 2 - КЛИЕНТ 1:"
echo "═══════════════════════════════════════════════════════════════"
echo "cd /Users/masha/battle_of_sea/client"
echo "dotnet run --project BattleOfSea.csproj"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Terminal 3 - КЛИЕНТ 2:"
echo "═══════════════════════════════════════════════════════════════"
echo "cd /Users/masha/battle_of_sea/client"
echo "dotnet run --project BattleOfSea.csproj"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Все использует порт: 5555"
echo "Оба клиента будут подключаться к ws://localhost:5555"
echo ""
